
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

import subprocess
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Карина\Desktop\Коды\assets rules\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1207x495")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 495,
    width = 1207,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    604.0,
    247.00000000000003,
    image=image_image_1
)

def close_and_open_window_menu():
    window.destroy()
    subprocess.Popen(['python','menu.py'])


canvas.create_text(
    563.0,
    12.0,
    anchor="nw",
    text="Правила игры",
    fill="#000000",
    font=("IrishGrover Regular", 24 * -1)
)

canvas.create_rectangle(
    12.0,
    49.0,
    1207.0,
    474.0,
    fill="#F5F5F5",
    outline="")

image_image_9 = PhotoImage(
    file=relative_to_assets("image_10.png"))
image_2 = canvas.create_image(
    944.0,
    262.0,
    image=image_image_9
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_1 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=close_and_open_window_menu,
    relief="flat"
)
button_1.place(
    x=1003.0,
    y=12.0,
    width=173.0,
    height=29.0
)

image_image_10 = PhotoImage(
    file=relative_to_assets("image_9.png"))
image_3 = canvas.create_image(
    341.0,
    248.0,
    image=image_image_10
)
window.resizable(False, False)
window.mainloop()
